--------------------------------------------------------
--  DDL for Table MEMBER_SECONDHANDSHOP
--------------------------------------------------------

  CREATE TABLE "HR"."MEMBER_SECONDHANDSHOP" 
   (	"MEMBER_ID" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"PHONENUM" VARCHAR2(50 BYTE), 
	"BIRTHDATE" VARCHAR2(20 BYTE), 
	"POSTCODE" VARCHAR2(20 BYTE), 
	"MEMBERAUTH" VARCHAR2(3 BYTE), 
	"JOINDATE" DATE DEFAULT sysdate		
	, 
	"OUTDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.MEMBER_SECONDHANDSHOP
SET DEFINE OFF;
Insert into HR.MEMBER_SECONDHANDSHOP (MEMBER_ID,PASSWORD,NAME,EMAIL,ADDRESS,PHONENUM,BIRTHDATE,POSTCODE,MEMBERAUTH,JOINDATE,OUTDATE) values ('test2','1234','test','w11@da.com','wwd','010-1111-1111','191919','dwada',null,to_date('19/10/10','RR/MM/DD'),null);
Insert into HR.MEMBER_SECONDHANDSHOP (MEMBER_ID,PASSWORD,NAME,EMAIL,ADDRESS,PHONENUM,BIRTHDATE,POSTCODE,MEMBERAUTH,JOINDATE,OUTDATE) values ('test1','1234','jjjjjjj','ka@nadi.com','qwe','010-1111-1111','qweq','13',null,to_date('19/10/07','RR/MM/DD'),null);
Insert into HR.MEMBER_SECONDHANDSHOP (MEMBER_ID,PASSWORD,NAME,EMAIL,ADDRESS,PHONENUM,BIRTHDATE,POSTCODE,MEMBERAUTH,JOINDATE,OUTDATE) values ('admin','admin','Manager','manager@secShop.com','none','03-1158-7894','0928','148-2244','1',to_date('19/10/07','RR/MM/DD'),null);
Insert into HR.MEMBER_SECONDHANDSHOP (MEMBER_ID,PASSWORD,NAME,EMAIL,ADDRESS,PHONENUM,BIRTHDATE,POSTCODE,MEMBERAUTH,JOINDATE,OUTDATE) values ('test3','3333','test3','test3@da.com','nadjawnjkda3-33-3','010-3333-3333','191013','131-3335',null,to_date('19/10/14','RR/MM/DD'),null);
Insert into HR.MEMBER_SECONDHANDSHOP (MEMBER_ID,PASSWORD,NAME,EMAIL,ADDRESS,PHONENUM,BIRTHDATE,POSTCODE,MEMBERAUTH,JOINDATE,OUTDATE) values ('test4','1234','test4','w4@da.com','dawdwadadawdwa','010-1111-2222','191219','123-0595',null,to_date('19/10/14','RR/MM/DD'),null);
--------------------------------------------------------
--  DDL for Index SYS_C007073
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007073" ON "HR"."MEMBER_SECONDHANDSHOP" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MEMBER_SECONDHANDSHOP
--------------------------------------------------------

  ALTER TABLE "HR"."MEMBER_SECONDHANDSHOP" ADD PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."MEMBER_SECONDHANDSHOP" MODIFY ("BIRTHDATE" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBER_SECONDHANDSHOP" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBER_SECONDHANDSHOP" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBER_SECONDHANDSHOP" MODIFY ("PASSWORD" NOT NULL ENABLE);
