--------------------------------------------------------
--  DDL for Table PRODUCT_SEC
--------------------------------------------------------

  CREATE TABLE "HR"."PRODUCT_SEC" 
   (	"PROD_NUM" NUMBER, 
	"PROD_SELLID" VARCHAR2(20 BYTE), 
	"PROD_CATEGORY" VARCHAR2(100 BYTE), 
	"PROD_NAME" VARCHAR2(100 BYTE), 
	"PROD_PRICE" VARCHAR2(100 BYTE), 
	"PROD_INFO" CLOB, 
	"PROD_DELITYPE" VARCHAR2(4 BYTE) DEFAULT 1, 
	"PROD_DELIPLACE" VARCHAR2(200 BYTE), 
	"PROD_INPUTDATE" DATE DEFAULT sysdate, 
	"PROD_ORIGINALFILE" VARCHAR2(200 BYTE), 
	"PROD_SAVEDFILE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PROD_INFO") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into HR.PRODUCT_SEC
SET DEFINE OFF;
Insert into HR.PRODUCT_SEC (PROD_NUM,PROD_SELLID,PROD_CATEGORY,PROD_NAME,PROD_PRICE,PROD_DELITYPE,PROD_DELIPLACE,PROD_INPUTDATE,PROD_ORIGINALFILE,PROD_SAVEDFILE) values (41,'test1','Soccer','Uniform','115000','1','california, us',to_date('19/10/16','RR/MM/DD'),'imgrc0124459720.jpg','20191016.jpg');
Insert into HR.PRODUCT_SEC (PROD_NUM,PROD_SELLID,PROD_CATEGORY,PROD_NAME,PROD_PRICE,PROD_DELITYPE,PROD_DELIPLACE,PROD_INPUTDATE,PROD_ORIGINALFILE,PROD_SAVEDFILE) values (44,'test2','BasketBall','BasketBall uniform','125000','1','california, us',to_date('19/10/16','RR/MM/DD'),'2019-New-Design-Sublimation-Basketball-Uniform.jpg','201910161571158100338.jpg');
Insert into HR.PRODUCT_SEC (PROD_NUM,PROD_SELLID,PROD_CATEGORY,PROD_NAME,PROD_PRICE,PROD_DELITYPE,PROD_DELIPLACE,PROD_INPUTDATE,PROD_ORIGINALFILE,PROD_SAVEDFILE) values (45,'test4','VolleyBall','VolleyBall','50000','1','california, us',to_date('19/10/16','RR/MM/DD'),'71kjs9OiBdL._SX425_.jpg','201910161571158190985.jpg');
Insert into HR.PRODUCT_SEC (PROD_NUM,PROD_SELLID,PROD_CATEGORY,PROD_NAME,PROD_PRICE,PROD_DELITYPE,PROD_DELIPLACE,PROD_INPUTDATE,PROD_ORIGINALFILE,PROD_SAVEDFILE) values (46,'test4','VolleyBall','VolleyBall Uniform','105000','2','california, us',to_date('19/10/16','RR/MM/DD'),'HTB1TM62DrSYBuNjSspiq6xNzpXay.jpg','201910161571158245862.jpg');
Insert into HR.PRODUCT_SEC (PROD_NUM,PROD_SELLID,PROD_CATEGORY,PROD_NAME,PROD_PRICE,PROD_DELITYPE,PROD_DELIPLACE,PROD_INPUTDATE,PROD_ORIGINALFILE,PROD_SAVEDFILE) values (42,'test1','BaseBall','BaseBall Glove','50000','2','oklahoma, us',to_date('19/10/16','RR/MM/DD'),'81ZSmQPTGGL._SX425_.jpg','201910161571157948553.jpg');
--------------------------------------------------------
--  DDL for Index SYS_C007118
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007118" ON "HR"."PRODUCT_SEC" ("PROD_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PRODUCT_SEC
--------------------------------------------------------

  ALTER TABLE "HR"."PRODUCT_SEC" ADD PRIMARY KEY ("PROD_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."PRODUCT_SEC" MODIFY ("PROD_INFO" NOT NULL ENABLE);
  ALTER TABLE "HR"."PRODUCT_SEC" MODIFY ("PROD_PRICE" NOT NULL ENABLE);
  ALTER TABLE "HR"."PRODUCT_SEC" MODIFY ("PROD_NAME" NOT NULL ENABLE);
  ALTER TABLE "HR"."PRODUCT_SEC" MODIFY ("PROD_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "HR"."PRODUCT_SEC" MODIFY ("PROD_SELLID" NOT NULL ENABLE);
